const translations = {
  fr: {
    about: "À propos",
    services: "Services",
    gallery: "Galerie",
    contact: "Contact",
    "hero-title": "Shabunda Minerals and Logistics Ltd",
    "hero-sub": "Exploiter la richesse minérale de l'Afrique avec fiabilité et durabilité",
    "hero-btn": "Partenariat",
    "about-title": "À propos de nous",
    "about-text1": "Nous sommes engagés à transformer le transport des minéraux en Afrique.",
    "about-text2": "Nos opérations couvrent les zones minières et les centres logistiques internationaux.",
    "services-title": "Nos Services",
    service1: "Logistique sur site minier",
    service2: "Flotte de transport terrestre",
    service3: "Solutions de fret aérien",
    service4: "Optimisation de la chaîne d'approvisionnement",
    service5: "Exportation et documentation",
    "services-desc": "Nous assurons une logistique fluide et conforme de la mine au marché.",
    "gallery-title": "Galerie",
    "contact-title": "Contactez-nous",
    "contact-desc": "Prêt à collaborer ou avez-vous des questions ?",
    "contact-btn": "Envoyer",
    "location-label": "Adresse",
    "phone-label": "Téléphone",
    "email-label": "Email",
    footer: "© 2025 Shabunda Minerals and Logistics Ltd. Tous droits réservés."
  },
  de: {
    about: "Über uns",
    services: "Dienstleistungen",
    gallery: "Galerie",
    contact: "Kontakt",
    "hero-title": "Shabunda Minerals and Logistics GmbH",
    "hero-sub": "Afrikas Mineralreichtum mit Vertrauen und Nachhaltigkeit fördern",
    "hero-btn": "Partner werden",
    "about-title": "Über uns",
    "about-text1": "Wir revolutionieren den Mineraltransport und die Logistik in Afrika.",
    "about-text2": "Unsere Aktivitäten erstrecken sich über Bergbaugebiete und internationale Knotenpunkte.",
    "services-title": "Unsere Dienstleistungen",
    service1: "Logistik an der Mine",
    service2: "Bodenflotte",
    service3: "Luftfrachtlösungen",
    service4: "Lieferkettenoptimierung",
    service5: "Export & Dokumentation",
    "services-desc": "Wir garantieren einen nahtlosen, konformen Ablauf vom Bergwerk bis zum Markt.",
    "gallery-title": "Galerie",
    "contact-title": "Kontaktieren Sie uns",
    "contact-desc": "Bereit zur Zusammenarbeit oder Fragen zu unseren Diensten?",
    "contact-btn": "Nachricht senden",
    "location-label": "Adresse",
    "phone-label": "Telefon",
    "email-label": "E-Mail",
    footer: "© 2025 Shabunda Minerals and Logistics GmbH. Alle Rechte vorbehalten."
  },
  es: {
    about: "Acerca de",
    services: "Servicios",
    gallery: "Galería",
    contact: "Contacto",
    "hero-title": "Shabunda Minerals and Logistics Ltd",
    "hero-sub": "Impulsando la riqueza mineral de África con confianza y sostenibilidad",
    "hero-btn": "Asociarse con nosotros",
    "about-title": "Quiénes somos",
    "about-text1": "Transformamos la logística minera y de transporte en África.",
    "about-text2": "Operamos en zonas mineras, fronteras e intercambios globales.",
    "services-title": "Nuestros Servicios",
    service1: "Logística en sitio minero",
    service2: "Flota terrestre",
    service3: "Transporte aéreo",
    service4: "Optimización de cadena de suministro",
    service5: "Exportación y documentación",
    "services-desc": "Garantizamos logística fluida y cumplimiento desde la mina al mercado.",
    "gallery-title": "Galería",
    "contact-title": "Contáctanos",
    "contact-desc": "¿Listo para colaborar o tienes preguntas?",
    "contact-btn": "Enviar mensaje",
    "location-label": "Ubicación",
    "phone-label": "Teléfono",
    "email-label": "Correo electrónico",
    footer: "© 2025 Shabunda Minerals and Logistics Ltd. Todos los derechos reservados."
  },
  it: {
    about: "Chi siamo",
    services: "Servizi",
    gallery: "Galleria",
    contact: "Contatto",
    "hero-title": "Shabunda Minerals and Logistics Ltd",
    "hero-sub": "Guidiamo la ricchezza mineraria africana con fiducia e sostenibilità",
    "hero-btn": "Collabora con noi",
    "about-title": "Chi siamo",
    "about-text1": "Trasformiamo la logistica mineraria e il trasporto in Africa.",
    "about-text2": "Operiamo in siti minerari e hub internazionali.",
    "services-title": "I nostri servizi",
    service1: "Logistica del sito minerario",
    service2: "Flotta di trasporto",
    service3: "Soluzioni di trasporto aereo",
    service4: "Ottimizzazione della catena di approvvigionamento",
    service5: "Esportazione e documentazione",
    "services-desc": "Garantiamo una logistica fluida e conforme dalla miniera al mercato.",
    "gallery-title": "Galleria",
    "contact-title": "Contattaci",
    "contact-desc": "Pronto a collaborare o hai domande?",
    "contact-btn": "Invia messaggio",
    "location-label": "Indirizzo",
    "phone-label": "Telefono",
    "email-label": "Email",
    footer: "© 2025 Shabunda Minerals and Logistics Ltd. Tutti i diritti riservati."
  },
  ru: {
    about: "О нас",
    services: "Услуги",
    gallery: "Галерея",
    contact: "Контакт",
    "hero-title": "Шабунда Минералс и Логистика",
    "hero-sub": "Развиваем минеральные ресурсы Африки с доверием и устойчивостью",
    "hero-btn": "Сотрудничать с нами",
    "about-title": "О компании",
    "about-text1": "Мы трансформируем логистику и транспортировку минералов в Африке.",
    "about-text2": "Мы работаем в горнодобывающих регионах и на международных рынках.",
    "services-title": "Наши услуги",
    service1: "Логистика на месторождениях",
    service2: "Автопарк наземного транспорта",
    service3: "Воздушные перевозки",
    service4: "Оптимизация цепочки поставок",
    service5: "Экспорт и документация",
    "services-desc": "Обеспечиваем полное соответствие и надежную логистику от шахты до рынка.",
    "gallery-title": "Галерея",
    "contact-title": "Связаться с нами",
    "contact-desc": "Готовы сотрудничать или есть вопросы?",
    "contact-btn": "Отправить сообщение",
    "location-label": "Адрес",
    "phone-label": "Телефон",
    "email-label": "Электронная почта",
    footer: "© 2025 Shabunda Minerals and Logistics Ltd. Все права защищены."
  },
  zh: {
    about: "关于我们",
    services: "服务",
    gallery: "画廊",
    contact: "联系",
    "hero-title": "Shabunda 矿产与物流有限公司",
    "hero-sub": "以信任和可持续性推动非洲矿产资源",
    "hero-btn": "与我们合作",
    "about-title": "关于我们",
    "about-text1": "我们致力于改善非洲的矿产物流和运输系统。",
    "about-text2": "业务涵盖矿区、边境口岸及国际枢纽。",
    "services-title": "我们的服务",
    service1: "矿区物流服务",
    service2: "地面运输车队",
    service3: "航空货运解决方案",
    service4: "供应链优化",
    service5: "出口与文件处理",
    "services-desc": "确保从矿山到市场的高效合规物流流程。",
    "gallery-title": "画廊",
    "contact-title": "联系我们",
    "contact-desc": "准备合作或有疑问？",
    "contact-btn": "发送信息",
    "location-label": "地址",
    "phone-label": "电话",
    "email-label": "电子邮件",
    footer: "© 2025 Shabunda 矿产与物流有限公司 版权所有"
  },
  ar: {
    about: "من نحن",
    services: "خدماتنا",
    gallery: "معرض الصور",
    contact: "اتصل بنا",
    "hero-title": "شركة شابوندا للمعادن والخدمات اللوجستية",
    "hero-sub": "نقود ثروات أفريقيا المعدنية بثقة واستدامة",
    "hero-btn": "تعاون معنا",
    "about-title": "من نحن",
    "about-text1": "نُحدث ثورة في نقل وتوريد المعادن في أفريقيا.",
    "about-text2": "عملياتنا تمتد عبر مناطق التعدين والمراكز الدولية.",
    "services-title": "خدماتنا",
    service1: "الخدمات اللوجستية لمواقع التعدين",
    service2: "أسطول النقل البري",
    service3: "حلول الشحن الجوي",
    service4: "تحسين سلسلة الإمداد",
    service5: "التصدير والتوثيق",
    "services-desc": "نضمن لوجستيات متكاملة ومتوافقة من المنجم إلى السوق.",
    "gallery-title": "معرض الصور",
    "contact-title": "اتصل بنا",
    "contact-desc": "هل أنت مستعد للتعاون أو لديك استفسار؟",
    "contact-btn": "إرسال الرسالة",
    "location-label": "العنوان",
    "phone-label": "الهاتف",
    "email-label": "البريد الإلكتروني",
    footer: "© 2025 شركة شابوندا للمعادن والخدمات اللوجستية. جميع الحقوق محفوظة."
  }
};

function changeLanguage() {
  const lang = document.getElementById("language").value;
  const elements = document.querySelectorAll("[data-i18n]");

  elements.forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (translations[lang] && translations[lang][key]) {
      el.innerHTML = translations[lang][key];
    }
  });
}
